title: Yanke Wang's Homepage
page-top-title: Yanke Wang
top-section-bg-text: Computer Science
home-subtitle: Yanke Wang&ensp;|&ensp;王彥柯
copyright-text: '&copy; Yanke Wang 2023-2024. All Rights Reserved.'
